### ISSUE TITLE
프로젝트 생성

### ISSUE THREAD

**Issue by Jonny-Cho** [Jonny-Cho/commerce-service-discovery#1]
![image](https://user-images.githubusercontent.com/24591642/149331099-71c4e801-7286-49c2-b6b0-c964d505b7f7.png)

![image](https://user-images.githubusercontent.com/24591642/149331299-1872f7f0-8f4c-44f4-85b9-495ffa03fb97.png)

@EnableEurekaServer 추가

application.yml

```
server:
  port: 8761

spring:
  application:
    name: discoveryservice

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
```
